language: Android
sudo: false
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.0
  - android-25
  - extra-android-support
  - extra
  - sys-img-armeabi-v7a-android-21
  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - google-gdk-license-.+
before_script:
- echo n | android create avd -n test -f -t android-21 --abi default/armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - /usr/local/android-sdk/
notifications:
  slack:
    secure: WrQI043fxuAr16OJRpLHuruESvJYUQsG5gGzR+fIJj3WkYACCfE8mAaGrDa4ZQMJDx0WIdXyKaLT9JxdGiF9og3AIbbOUKVAgbKc3qi7GIYp5aaWObaKDJdljrhGJbVYlJO5kVwYi3jIBeNtpSCc8OHbz53KNACucVefXiHXSAPdurTipAvzOuS+J385OuXd2IwABtsWbQFqvnB6DYnPjjcwsBPKaV3CYCt7TgbdfuReO9wgTvkSS0gc0uByacJCqU/QaWZoQD7Ff4+2f//Xfzc1HGX9h/YNgazn8q/UxV1D9FR4ehWu6r6ka+PyOzHt2MZG94ktng60GzqXe4VcLHGCM13+w6DTiN1ItUmDGevTgAzBOjW+9cvwFy98QpLI3CFykKDyIHZ8GEoW7ls+R2Qx1E/PM4O1g2dsexi/eiunWMh7nmqsgurBh2x+xXKn8x97WdcrtkFhbtnFpXdTuGDekcAqX+5v3Zs8KCU1x8QOYh6zsWDCi5DSWZ07fZQRay/73U5xps6P3//L7iLXhlfJZu/3VqmdBiDNKKu2YMFQoje/wUeXvnkd+4n24kcjua6I9E2DSLiHcQAcflL/pD1lZi5tgHC182tiafWMsmUC6aV6JihoSIoG7+ZrL8hToSI/8zsEX5LlY9+wSjOHqVdQVZcDuEgVQW9iva+JXC8=
